import { useEffect, useRef, type CanvasHTMLAttributes } from "react";
import type { LightFieldShader } from "./light-field/dither.webgl.js";
import { useConfig, type ThemeMode } from "../../ConfigProvider";
import { cn } from "../../utils/cn";
import { shaderPalette } from "./palette";

export type LightFieldVariant = "dither" | "pure" | "grain" | "halftone";

export interface LightFieldProps
  extends Omit<CanvasHTMLAttributes<HTMLCanvasElement>, "onError"> {
  /** Post pass over the same 266° → 175° field. `dither` is the one the brand site ships. */
  variant?: LightFieldVariant;
  /** Force an appearance. Default follows the canvas's computed `color-scheme` (tokens, ConfigProvider, OS). */
  theme?: ThemeMode;
  /** `false` draws one still frame. Reduced motion always does. */
  autoplay?: boolean;
  /** WebGL2 missing or a shader failure; the CSS gradient fallback stays visible. */
  onError?: (error: Error) => void;
}

// Generated by synapseware-web/tools/light-field-gen from the OpenShaders name-card module (MIT):
//   node generate.mjs --seed synapseware --hue 266 --to 175 --effect dither   --out dither.webgl.js
//   node generate.mjs --seed lattice     --hue 266 --to 175 --effect none     --out pure.webgl.js
//   node generate.mjs --seed rack-a-01   --hue 266 --to 175 --effect grain    --out grain.webgl.js
//   node generate.mjs --seed wh1-a-12-03 --hue 266 --to 175 --effect halftone --out halftone.webgl.js
// Each variant is its own chunk; consumers that never render one pay nothing.
const modules: Record<LightFieldVariant, () => Promise<typeof import("./light-field/dither.webgl.js")>> = {
  dither: () => import("./light-field/dither.webgl.js"),
  pure: () => import("./light-field/pure.webgl.js"),
  grain: () => import("./light-field/grain.webgl.js"),
  halftone: () => import("./light-field/halftone.webgl.js"),
};

/** tokens.css sets `color-scheme` per appearance, so the computed value is the effective theme. */
function resolveTheme(el: HTMLElement): ThemeMode {
  return getComputedStyle(el).colorScheme.includes("dark") ? "dark" : "light";
}

/** The brand light field: light moving through paper or dark ground, navy → cyan → mint. Decorative; never behind text. */
export function LightField({
  variant = "dither",
  theme: themeProp,
  autoplay = true,
  onError,
  className,
  style,
  ...rest
}: LightFieldProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const shaderRef = useRef<LightFieldShader | null>(null);
  const { theme: configTheme } = useConfig();

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const controller = new AbortController();
    const fail = (error: unknown) =>
      onError?.(error instanceof Error ? error : new Error(String(error)));
    modules[variant]()
      .then(({ createShader }) => {
        if (controller.signal.aborted) return;
        shaderRef.current = createShader(canvas, {
          theme: themeProp ?? resolveTheme(canvas),
          background: { light: shaderPalette.paper, dark: shaderPalette.paperDark },
          autoplay,
          signal: controller.signal,
          onError: fail,
        });
      })
      .catch(fail);
    return () => {
      controller.abort();
      shaderRef.current = null;
    };
    // Theme changes are applied below with setTheme (a crossfade), not by rebuilding the shader.
  }, [variant, autoplay]);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const sync = () => shaderRef.current?.setTheme(themeProp ?? resolveTheme(canvas));
    sync();
    const scheme = window.matchMedia("(prefers-color-scheme: dark)");
    const root = new MutationObserver(sync);
    scheme.addEventListener("change", sync);
    root.observe(document.documentElement, { attributes: true, attributeFilter: ["data-theme"] });
    return () => {
      scheme.removeEventListener("change", sync);
      root.disconnect();
    };
  }, [themeProp, configTheme]);

  return (
    <canvas
      ref={canvasRef}
      aria-hidden="true"
      className={cn(
        // Brand guide: before the first frame, and without WebGL2, a gradient of blue-deep and cyan on paper.
        "block w-full rounded-none bg-[radial-gradient(120%_80%_at_20%_100%,var(--su-blue-deep),var(--su-cyan)_45%,var(--su-paper)_80%)]",
        className,
      )}
      style={{ width: "100%", height: 220, ...style }}
      {...rest}
    />
  );
}
