export const groups = {
  General: ["Button", "FloatButton", "Icon", "Typography"],
  Layout: ["Divider", "Flex", "Grid", "Layout", "Masonry", "Space", "Splitter"],
  Navigation: [
    "Anchor",
    "Breadcrumb",
    "Dropdown",
    "Menu",
    "Pagination",
    "Steps",
    "Tabs",
  ],
  "Data Entry": [
    "AutoComplete",
    "Cascader",
    "Checkbox",
    "ColorPicker",
    "DatePicker",
    "Form",
    "Input",
    "InputNumber",
    "Mentions",
    "Radio",
    "Rate",
    "Select",
    "Slider",
    "Switch",
    "TimePicker",
    "Transfer",
    "TreeSelect",
    "Upload",
  ],
  "Data Display": [
    "Avatar",
    "Badge",
    "Calendar",
    "Card",
    "Carousel",
    "Collapse",
    "Descriptions",
    "Empty",
    "Image",
    "List",
    "Listy",
    "Popover",
    "QRCode",
    "Segmented",
    "Statistic",
    "Table",
    "Tag",
    "Timeline",
    "Tooltip",
    "Tour",
    "Tree",
  ],
  Feedback: [
    "Alert",
    "Drawer",
    "Message",
    "Modal",
    "Notification",
    "Popconfirm",
    "Progress",
    "Result",
    "Skeleton",
    "Spin",
    "Watermark",
  ],
  Materials: ["Glass", "Chrome", "Surface"],
  Other: ["Affix", "App", "BorderBeam", "ConfigProvider"],
  Shaders: [
    "PaperTexture",
    "Dithering",
    "DotGrid",
    "MeshGradient",
    "NeuroNoise",
    "PulsingBorder",
    "Warp",
    "LightField",
  ],
} as const;
export const components = Object.entries(groups).flatMap(([category, names]) =>
  names.map((name) => ({ name, category })),
);
export type ComponentName = (typeof components)[number]["name"];
export const descriptions: Record<string, string> = {
  Button: "A clear next step. Familiar actions with just the right emphasis.",
  FloatButton: "Keep a primary action within reach, above the content.",
  Icon: "Small symbols. Clear meaning. A consistent stroke at every size.",
  Typography:
    "A considered type scale, from a quiet caption to a confident title.",
  Divider: "Give related content room to breathe.",
  Flex: "Align, distribute, and arrange content with flexible layouts.",
  Grid: "Build balanced layouts on a twenty-four column grid.",
  Layout: "A familiar structure for headers, sidebars, content, and footers.",
  Masonry: "Let uneven content find its natural rhythm.",
  Space: "Consistent spacing without repeated margin rules.",
  Splitter: "Let people choose how much space each pane needs.",
  Anchor: "Keep your place as you move through a page.",
  Breadcrumb: "A little context for every level of navigation.",
  Dropdown: "Put contextual actions exactly where they are needed.",
  Menu: "Organize destinations in a familiar navigation list.",
  Pagination: "Make a large collection feel manageable.",
  Steps: "A clear path from the first step to the finish.",
  Tabs: "Related views, one focused space.",
  AutoComplete: "Help people find the right value as they type.",
  Cascader: "Choose a destination through nested levels.",
  Checkbox: "One choice, or a few. Make each selection clear.",
  ColorPicker: "A simple way to choose and fine-tune a color.",
  DatePicker: "Pick a date with the browser's native date field.",
  Form: "Bring labels, validation, and inputs together.",
  Input: "A comfortable place for a thought, a name, or a search.",
  InputNumber: "Precise values with built-in minimums and maximums.",
  Mentions: "Bring people into the conversation with a simple @.",
  Radio: "Make a single choice from a set of options.",
  Rate: "Turn an opinion into an intuitive rating.",
  Select: "A considered alternative to the native select.",
  Slider: "Fine-tune a value with a smooth, direct gesture.",
  Switch: "A familiar on or off, with immediate feedback.",
  TimePicker: "Pick a time using the native clock interface.",
  Transfer: "Move selected items between two collections.",
  TreeSelect: "Find a value inside a nested collection.",
  Upload: "Add files with a click or a drag and drop.",
  Avatar: "A familiar face, with a thoughtful fallback.",
  Badge: "A small signal for something worth noticing.",
  Calendar: "See the month and select a day at a glance.",
  Card: "Give a piece of content a space of its own.",
  Carousel: "Move through a collection, one slide at a time.",
  Collapse: "Reveal the details when they become relevant.",
  Descriptions: "Bring structure to the details that matter.",
  Empty: "An empty space with a clear next step.",
  Image: "Display images with a graceful fallback.",
  List: "A simple, scannable collection of related items.",
  Listy: "A virtualized scroll area for longer collections.",
  Popover: "A little more context, without leaving the page.",
  QRCode: "Connect a screen to a scannable destination.",
  Segmented: "Switch between closely related views.",
  Statistic: "Make an important number easy to read.",
  Table: "Compare structured information, row by row.",
  Tag: "Small labels to organize a bigger picture.",
  Timeline: "Tell the story in the order it happened.",
  Tooltip: "A helpful hint, just when it is needed.",
  Tour: "Guide people through something new.",
  Tree: "Explore a hierarchy one branch at a time.",
  Alert: "Keep important context visible and close to the task.",
  Drawer: "Make room for a secondary task in a side panel.",
  Message: "A brief confirmation that the action worked.",
  Modal: "Bring one important decision into focus.",
  Notification: "A little more detail about a meaningful update.",
  Popconfirm: "A quick check before a consequential action.",
  Progress: "Show how far along a task has come.",
  Result: "A clear outcome and a way to move forward.",
  Skeleton: "Keep the shape of content while it loads.",
  Spin: "A quiet indication that work is in progress.",
  Watermark: "Apply a repeating mark over content.",
  Glass: "Blurred material for floating and sticky chrome.",
  Chrome: "A hairline rim around a surface someone else sizes.",
  Surface: "The content layer: a tone, and depth drawn in hairlines.",
  Affix: "Keep useful controls in view as content scrolls.",
  App: "Shared access to messages and modal actions.",
  BorderBeam: "A moving highlight around a featured element.",
  ConfigProvider: "One place for theme and design token configuration.",
  PaperTexture: "Quiet paper fiber — content-layer atmosphere without chrome.",
  Dithering: "Print-like dither in action blue on paper.",
  DotGrid: "A square plot grid for instrument panels and bays.",
  MeshGradient: "A soft brand field — paper, mint beam, scarce action.",
  NeuroNoise: "Instrument web of mint beam over navy depth.",
  PulsingBorder: "Square frame with mint and action beam spots.",
  Warp: "A restrained scan field warped from navy to mint.",
  LightField:
    "The brand light field — navy to mint through paper or dark ground, in four post passes.",
};
